name: mydoctor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.6.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.8
  url_launcher: ^6.3.2
  typed_data: ^1.4.0
  open_filex: ^4.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
